export const RouterConstantUtil = {
  page: {
    notFound: "*",
    home: "/",
    aroundYou: "/around",
    recommended: "/recommended",
    topRated: "/top-rated",
    profile: "/profile",
    services: "/services",
    artisan: "/artisan",
    mybookings: "/my-bookings",
    booking: "/booking",
    messages: "/messages",
    account: "/account",
    settings: "/settings",
    report: "/report-issue",
    privacy: "/privacy-policy",
    cancellation: "/cancellation-policy",
    about: "/about",
    auth: {
      login: "/auth/login",
      signup: "/auth/signup",
      resetpassword: "/auth/reset-password",
    },
  },
};
