import type { Review } from "types/global";

export const aroundYouProviders = [
  {
    id: "1",
    name: "Elijah Mboto",
    avatar: "/images/user.jpg",
    rating: 4.2,
    service: "Plumber",
    price: 2500,
    isVerified: true,
  },
  {
    id: "2",
    name: "Emmanuel Sara",
    avatar: "/images/user.jpg",
    rating: 4.2,
    service: "Home & Cleaning",
    price: 2500,
    isVerified: false,
  },
  {
    id: "3",
    name: "Elijah Mboto",
    avatar: "/images/user.jpg",
    rating: 4.2,
    service: "Plumber",
    price: 2500,
    isVerified: true,
  },
  {
    id: "4",
    name: "Elias Mboto",
    avatar: "/images/user.jpg",
    rating: 4.7,
    service: "Plumber",
    price: 10500,
    isVerified: true,
  },
];

export const recommendedProviders = [
  {
    id: "5",
    name: "Nwankwo Kennedy",
    avatar: "/images/user.jpg",
    mainImage: "/images/artisan.png",
    rating: 4.2,
    service: "Repairs & Fixes",
    price: 2500,
    distance: "3km",
    tasksCompleted: 145,
  },
  {
    id: "6",
    name: "Joshua Nana",
    avatar: "/images/user.jpg",
    mainImage: "/images/artisan.png",
    rating: 4.1,
    service: "Home & Cleaning",
    price: 1500,
    distance: "2km",
    tasksCompleted: 89,
  },
  {
    id: "7",
    name: "Oluwaseun Wale",
    avatar: "/images/user.jpg",
    mainImage: "/images/artisan.png",
    rating: 4.4,
    service: "Gadgets & Delivery",
    price: 4500,
    distance: "1km",
    tasksCompleted: 203,
  },
  {
    id: "8",
    name: "Oluwaseun Wale",
    avatar: "/images/user.jpg",
    mainImage: "/images/artisan.png",
    rating: 4.4,
    service: "Gadgets & Delivery",
    price: 4500,
    distance: "1km",
    tasksCompleted: 203,
  },
];

export const topRatedProviders = [
  {
    id: "8",
    name: "Nwankwo Kennedy",
    avatar: "/images/user.jpg",
    mainImage: "/images/artisan2.jpg",
    rating: 5.0,
    service: "Mechanic",
    price: 2500,
    distance: "3km",
    tasksCompleted: 145,
  },
  {
    id: "9",
    name: "Sarah Johnson",
    avatar: "/images/user.jpg",
    mainImage: "/images/artisan2.jpg",
    rating: 4.9,
    service: "Home Cleaning",
    price: 2500,
    distance: "1.5km",
    tasksCompleted: 220,
  },
  {
    id: "10",
    name: "Mike Anderson",
    avatar: "/images/user.jpg",
    mainImage: "/images/artisan2.jpg",
    rating: 4.8,
    service: "Home Cleaning",
    price: 2500,
    distance: "2km",
    tasksCompleted: 167,
  },
  {
    id: "11",
    name: "David Wilson",
    avatar: "/images/user.jpg",
    mainImage: "/images/artisan2.jpg",
    rating: 4.9,
    service: "Home Cleaning",
    price: 2500,
    distance: "2.5km",
    tasksCompleted: 298,
  },
];

export const reviewsData: Review[] = [
  {
    id: "1",
    customerName: "Chika O",
    customerAvatar: "/images/user1.png",
    rating: 5,
    review:
      "Nora came through in less than an hour and got my car running again without needing a tow. Very polite and knew exactly what was wrong. Will definitely call again",
    location: "Awka, Anambra State",
    date: "2nd May, 2025",
  },
  {
    id: "2",
    customerName: "Emeka B.",
    customerAvatar: "/images/user1.png",
    rating: 4.1,
    review:
      "He diagnosed the issue correctly and fixed it, but the job took longer than expected. Still, I appreciate the honesty and solid work.",
    location: "Abakpa, Enugu State",
    date: "2nd May, 2025",
  },
  {
    id: "3",
    customerName: "Tosin A.",
    customerAvatar: "/images/user1.png",
    rating: 5,
    review:
      "Very knowledgeable, came fully prepared, and even gave me tips on how to maintain my brakes better. Highly recommend!",
    location: "Ibadan, Oyo State",
    date: "2nd May, 2025",
  },
  {
    id: "4",
    customerName: "Ify M.",
    customerAvatar: "/images/user1.png",
    rating: 3,
    review:
      "The repair was okay, but communication could have been better. I had to follow up twice to confirm the appointment time.",
    location: "Awka, Anambra State",
    date: "2nd May, 2025",
  },
  {
    id: "5",
    customerName: "Emeka B.",
    customerAvatar: "/images/user1.png",
    rating: 4.1,
    review:
      "He diagnosed the issue correctly and fixed it, but the job took longer than expected. Still, I appreciate the honesty and solid work.",
    location: "Abakpa, Enugu State",
    date: "2nd May, 2025",
  },
  {
    id: "6",
    customerName: "Ify M.",
    customerAvatar: "/images/user1.png",
    rating: 3,
    review:
      "The repair was okay, but communication could have been better. I had to follow up twice to confirm the appointment time.",
    location: "Awka, Anambra State",
    date: "2nd May, 2025",
  },
];
